### ISSUE TITLE
Premature end of wav file (v1.5.0)

### ISSUE THREAD

**Issue by berarma** [agateau/sfxr-qt#22]
When trying to open saved wav files in Godot or with Sox I get this error.

**Comment by agateau** [comment]
Hi, can you attach the file in both sfxj and wav formats, so that I can reproduce? (You might need to zip them for GitHub to accept them)

**Comment by berarma** [comment]
It only happens when setting the sample rate to 22050Hz. Sorry for missing that information, I didn't know.

Example added: [hit.zip](https://github.com/user-attachments/files/15897354/hit.zip)

**Comment by agateau** [comment]
Should be good now :crossed_fingers:.
