### ISSUE TITLE
Doesn't look good with dark KDE themes.

### ISSUE THREAD

**Issue by ongun-kanat** [agateau/sfxr-qt#3]
I don't know how to set themes with QtQuick (if i could, this were a pull request) but with Breeze dark colorscheme in KDE it's almost unreadable. 

It's quite nice and simple application. I loved it. Maybe it's audience is somewhat niche yet, it's certainly useful and fun.

**Comment by agateau** [comment]
Hi!
Which version of Plasma are you using? I just tried Breeze dark here (old install with Plasma 5.9.4, Qt 5.7.1) and QtQuick just ignore the color palette, it looks just like the screenshot on the front page. While it's sad the palette is ignored, it's definitely readable.

Can you post a screenshot of how it looks for you?

**Comment by ongun-kanat** [comment]
It's Plasma 5.12 and Qt 5.10 here.

![screenshot_20180211_145231](https://user-images.githubusercontent.com/3601965/36073061-64b79a6a-0f3b-11e8-9943-8fdb04b25aa0.png)

**Comment by agateau** [comment]
Wow, indeed that is unreadable. I suspect this is an issue of QtQuick Controls2 "default" style. You can switch the style at runtime using the `-style` option. I just tried with `-style material` (looks meh) and `-style universal` (looks ok). You can try one of those.

Qt 5.10 comes with the Fusion style which is supposed to give a desktop-oriented look'n'feel. So you can also try running SFXR Qt with `-style fusion`.

(More details here: https://doc.qt.io/qt-5/qtquickcontrols2-styles.html)

**Comment by Dariasteam** [comment]
It gives me "QApplication: invalid style override passed, ignoring it." when passing 'material' or 'universal' to style flag and in both cases the app looks the same as without flags 

https://imgur.com/a/3GzD9

For 'fusion' style it only changes a bit the shape of the sliders and buttons but the colors remain the same. I'm using kvantum theme but the same happens with breeze dark

**Comment by agateau** [comment]
Maybe material and universal themes are in a different package on your system?

**Comment by Dariasteam** [comment]
I'm on arch, it looks like it's included in [qt5-quickcontrols2 5.10.0-1](https://www.archlinux.org/packages/extra/x86_64/qt5-quickcontrols2/files/) which I have installed. Maybe I'm missing something 🤔

**Comment by agateau** [comment]
I can't help you there, I am on Kubuntu.

**Comment by ongun-kanat** [comment]
Doesn't Qt Quick apps follow system style? It looked somewhat unnecessary to set another non system style for QtQuick. It would be so annoying for Kirigami KDE Framework devs to bother with styles. Kirigami works okay for me so bug might be somewhere else.

@agateau This PPA provides Qt 5.10 and qtcreator and it doesn't interfere with system's Qt.  I personally use those packages on my work laptop. Can you compile it using this version?
https://launchpad.net/~beineri/+archive/ubuntu/opt-qt-5.10.0-xenial
Maybe it's a fault/bug in Qt. Qt 5.8 had hell a lot of bugs it might be one of its remnants.
