### ISSUE TITLE
Randomize feature restored

### ISSUE THREAD

**Issue by xandark** [agateau/sfxr-qt#6]
Is it too much to ask to have the Randomize button/feature? I often used this to discover new sounds that I would never have iteratively worked into existence.

**Comment by agateau** [comment]
Hi! I considered it, but I felt it "Mutate" was random enough. Did Randomize produce much different sounds for you?

**Comment by xandark** [comment]
Oh yes, very different and often surprising!

I also remember reading that the developers at Williams when then were coming up with the sfx for the old arcade games would power cycle their equipment, which would load arbitrary parameters into memory and they would discover sounds that made it into the final games. This is how I feel with the Randomize button in other versins of sfxr.

**Comment by agateau** [comment]
Nice story about Williams, that's a very bare-metal way to generate random values :)

Anyway, I just added back the Randomize button.
