### ISSUE TITLE
Fails tests on some architectures

### ISSUE THREAD

**Issue by alexmyczko** [agateau/sfxr-qt#7]
Hello @agateau 

Thank you for the software. Meanwhile it's in Debian, however tests fail on some machines, here's the details:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=997033

and here the overview:

https://buildd.debian.org/status/package.php?p=sfxr-qt&suite=sid

**Comment by agateau** [comment]
Hi, thanks for letting me know about that issue. I'd like to look into it, but I could use some help regarding setup. What's the simplest way to reproduce this bug. I guess I can setup a QEmu big-endian VM, but maybe there is a ready-to-use tool?

**Comment by alexmyczko** [comment]
once you have installed a debian stable (bullseye), you change `/etc/apt/sources.list` to be:

```
deb http://debian.ethz.ch/debian sid main contrib non-free
#deb http://debian.ethz.ch/debian experimental main contrib non-free
#deb-src http://debian.ethz.ch/debian sid main contrib non-free
#deb-src http://debian.ethz.ch/debian experimental main contrib non-free
```

then run `apt-get update; apt-get dist-upgrade`, start from there...

**Comment by agateau** [comment]
Actually I was more thinking about an easier way to setup the QEmu VM :). Anyway, I found some tutorial, going to follow them.

**Comment by agateau** [comment]
I haven't yet managed to install a VM :(, but I rewrote the failing code to use endian-independent APIs from Qt instead of the libc API. Do you have a way to try the `wavsaver-qiodevice` branch on a big-endian machine?

**Comment by agateau** [comment]
OK. I spent my weekend trying to install that VM. One of the installer images I tried fails to install grub, the other fails to install a working package repository. I am not wasting any more time on that.

I just merged that `wavsaver-qiodevice` branch. Hopefully the fixes are good enough. Let me know if it fixes the problem or if you have a way for me to get access to a big-endian system.

**Comment by alexmyczko** [comment]
https://buildd.debian.org/status/package.php?p=sfxr-qt&suite=sid
bad luck :(

**Comment by agateau** [comment]
This one is easier. Can you try master again?
